# Generated by Django 5.2.5 on 2026-10-07 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Type de lien', max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('TXT', 'Hypertext'), ('MEDIA', 'Media'), ('URL', 'Website')])),
                ('path', models.CharField(error_messages={'double': 'File already exists in database'}, help_text='Please, indicate a path or url.', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(error_messages={'double': 'File already exists in database'}, help_text='Please, indicate a path or url.', null=True, unique=True)),
                ('type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('AUD', 'Audio'), ('VID', 'Video')])),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, unique=True)),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.link')),
                ('medias', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.media')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(error_messages={'double': 'File already exists in database'}, max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(max_length=128, unique=True)),
                ('components', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.bloc')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(max_length=128, unique=True)),
                ('sections', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.section')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='containers',
            field=models.ManyToManyField(related_name='medias', through='core.Section', to='core.media'),
        ),
        migrations.AddField(
            model_name='link',
            name='containers',
            field=models.ManyToManyField(related_name='links', through='core.Section', to='core.link'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('content', models.TextField(unique=True)),
                ('containers', models.ManyToManyField(related_name='texts', through='core.Section', to='core.text')),
            ],
        ),
        migrations.AddField(
            model_name='bloc',
            name='texts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='core.text'),
        ),
    ]
