# Generated by Django 5.2.5 on 2026-10-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('path', models.CharField(error_messages={'double': 'File already exists in database'}, help_text='Please, indicate a path or url.', null=True, unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Type de lien', max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('path', models.CharField(error_messages={'double': 'File already exists in database'}, help_text='Please, indicate a path or url.', unique=True)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bloc')),
                ('label', models.ForeignKey(default='undefined-link', max_length=128, on_delete=django.db.models.deletion.PROTECT, to='core.text')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='links',
            field=models.ManyToManyField(related_name='used_in', to='core.link'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='pointer',
            field=models.ManyToManyField(related_name='targets', to='core.link'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='medias',
            field=models.ManyToManyField(related_name='used_in', to='core.media'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(error_messages={'double': 'File already exists in database'}, max_length=64, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(max_length=128, unique=True)),
                ('components', models.ManyToManyField(related_name='used_in', to='core.bloc')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bloc',
            name='texts',
            field=models.ManyToManyField(related_name='used_in', to='core.text'),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('nature', models.CharField(choices=[('WEB', 'Format Web'), ('DOC', 'Format Papier'), ('DEFAULT', 'Unset')], default='DEFAULT')),
                ('description', models.TextField(max_length=128, unique=True)),
                ('sections', models.ManyToManyField(related_name='used_in', to='core.section')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type'),
        ),
    ]
