# Generated by Django 5.2.5 on 2026-10-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='famille',
            field=models.CharField(choices=[('TITLE', 'Titre'), ('CORPS', 'Corps de texte'), ('LABEL', 'Label'), ('CTA', 'Call To Action'), ('DEFAULT', 'Unset')], default='DEFAULT'),
        ),
    ]
