# Generated by Django 5.2.5 on 2026-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_text_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
