# Generated by Django 5.2.5 on 2026-10-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_text_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='media',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='text',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='links',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='medias',
        ),
        migrations.RemoveField(
            model_name='bloc',
            name='texts',
        ),
        migrations.RemoveField(
            model_name='page',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='components',
        ),
        migrations.AddField(
            model_name='bloc',
            name='links',
            field=models.ManyToManyField(related_name='used_in', to='core.link'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='medias',
            field=models.ManyToManyField(related_name='used_in', to='core.media'),
        ),
        migrations.AddField(
            model_name='bloc',
            name='texts',
            field=models.ManyToManyField(related_name='used_in', to='core.text'),
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(related_name='used_in', to='core.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='components',
            field=models.ManyToManyField(related_name='used_in', to='core.bloc'),
        ),
    ]
