# Generated by Django 5.2.5 on 2026-10-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_link_containers_remove_media_containers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='type',
            field=models.CharField(choices=[('HEADER', 'Header'), ('MENU', 'Menu'), ('LABEL', 'Label'), ('CTA', 'Call To Action'), ('DEFAULT', 'Unset')], default='DEFAULT', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nature',
            field=models.CharField(choices=[('WEB', 'Format Web'), ('DOC', 'Format Papier'), ('DEFAULT', 'Unset')], default='DEFAULT'),
        ),
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('PRIMARY', 'Main Content'), ('SECOND', 'Secondary Content'), ('MANDATORY', 'Mandatory Content'), ('ADD', 'Suggested Content'), ('DEFAULT', 'Unset')], default='DEFAULT'),
        ),
    ]
