# Generated by Django 5.2.5 on 2026-10-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bloc_type_page_nature_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloc',
            name='pointer',
            field=models.ManyToManyField(related_name='targets', to='core.link'),
        ),
        migrations.AddField(
            model_name='link',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bloc'),
        ),
    ]
