# Generated by Django 5.2.5 on 2026-10-08 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bloc_pointer_link_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='famille',
        ),
        migrations.AlterField(
            model_name='link',
            name='label',
            field=models.ForeignKey(default='undefined-link', max_length=128, on_delete=django.db.models.deletion.PROTECT, to='core.text'),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('AUD', 'Audio'), ('VID', 'Video'), ('DEFAULT', 'Unset')], default='DEFAULT'),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128, unique=True)),
                ('parent', models.ManyToManyField(to='core.type')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.type'),
        ),
    ]
