# Generated by Django 5.2.5 on 2026-10-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_text_famille_alter_link_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='parent',
            field=models.ManyToManyField(default=1, null=True, to='core.type'),
        ),
    ]
