# Generated by Django 5.2.5 on 2026-10-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_type_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='parent',
        ),
    ]
